#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += rm68200_hd720_dsi_vdo_cmi_chuangyu_cy50hda203v1_mx2118b_jd_ht5001k.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/



