#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += otm8012a_fwvga_dsi_cmd_boe_yxd_y83330_72m_mx2103.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/



