#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += ili9885_fhd_dsi_vdo_auo_hz_hfh55050fpca_mx2103fd_hbbd_m6b.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/


