#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += ili9881c_hd720_dsi_vdo_hsd_hz_hhd55144_mx2132e_ares_a5508.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
