#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += rm68172_fwvga_dsi_vdo_tm_baoxu_tm045ydh2600_mx2103_smt.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/


