#
# Makefile for misc devices that really don't fit anywhere else.
#


obj-y += st7701_wvga_ctc_vdo_yixinda_for_mx2131f_i589.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
