#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += nt35532_fhd_dsi_vdo_panda_yixinda_for_w5503.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/


