#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += ili9881c_hd720_dsi_vdo_ivo_bx_bx50005525_mx1091e_wpf_d5028b.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
