#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y +=ili9807_qhd_dsi_vdo_auo_wcl_w552200aaa_mx2126e_sop_c6.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/



