/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bird_flashlight_FlashLightJni */

#ifndef _Included_com_bird_flashlight_FlashLightJni
#define _Included_com_bird_flashlight_FlashLightJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bird_flashlight_FlashLightJni
 * Method:    turn_on_flashlight
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_bird_flashlight_FlashLightJni_turn_1on_1flashlight
  (JNIEnv *, jclass);

/*
 * Class:     com_bird_flashlight_FlashLightJni
 * Method:    turn_off_flashlight
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_bird_flashlight_FlashLightJni_turn_1off_1flashlight
  (JNIEnv *, jclass);

/*
 * Class:     com_bird_flashlight_FlashLightJni
 * Method:    get_state_flashlight
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_bird_flashlight_FlashLightJni_get_1state_1flashlight
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
