#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += jd9365_hd720_dsi_vdo_ivo_songrui_050rivd94_mx2521e_yaao_x27.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
