#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += nt35521sh_hd720_dsi_vdo_kyd_boe_bv050hden40_mx2126_sop_c6.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
