#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += jd9365_hd720_dsi_vdo_ivo_bx_55008030b_mx2521e_v01_wpf_d5517.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
