#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += jd9161ba_fwvga_dsi_vdo_ivo_zgd_t050k409fpc_mx2128e_als_a5066.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/



