#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += ili9885_qhd_dsi_vdo_xp_dt_dt552xxuv0_mx2120e_hds_s702.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
