#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += nt35521_hd720_dsi_vdo_kyd_boe_for_mx2109e_sop_p2.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
