#[BIRD][内单项目][BIRD_INTERNAL_SALE_STATISTICS]BEGIN
ifeq ($(BIRD_INTERNAL_SALE_STATISTICS),yes)
LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := SalesCount
LOCAL_SRC_FILES := SalesCount.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := platform
include $(BUILD_PREBUILT)
endif
#[BIRD][内单项目][BIRD_INTERNAL_SALE_STATISTICS]BEGIN

