#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += ili9806e_fwvga_dsi_vdo_ivo_bx_bx49505325c_mx2150p_jy_a5010.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/



