#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += fl10802_fwvga_dsi_vdo_boe_jj_fpct50v254v1_mx2109f_ares_a5085_for_mx2132er.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/



