#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += fl11281_hd720_dsi_vdo_cpt_gongtai_xxx_mx2132er_sy_f10.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/



