#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += ili9806e_wvga_hsb6c_vdo_hlt_mx2131f_szbd_s45269_smt.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/


