#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += jd9161ba_fwvga_dsi_vdo_ivo_ips_c050swyg_mx2150p_wpf_d5033.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/



