#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += ili9881c_hd720_dsi_vdo_ivo_bx_c050s050k_mx2128e_v02_jd_jd5002.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
