#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += ili9881c_hd720_dsi_vdo_qicai_mx1091f_f511.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
