/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nbbsw_mmi_test_MMITestNative */

#ifndef _Included_com_bird_mmi_test_MMITestNative
#define _Included_com_bird_mmi_test_MMITestNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nbbsw_mmi_test_MMITestNative
 * Method:    device_test_led_r_on_jni
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_bird_mmi_1test_MMITestNative_device_1test_1led_1r_1on_1jni
  (JNIEnv *, jclass);

/*
 * Class:     com_nbbsw_mmi_test_MMITestNative
 * Method:    device_test_led_r_off_jni
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_bird_mmi_1test_MMITestNative_device_1test_1led_1r_1off_1jni
  (JNIEnv *, jclass);

/*
 * Class:     com_nbbsw_mmi_test_MMITestNative
 * Method:    device_test_keypad_bk_turn_on_jni
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_bird_mmi_1test_MMITestNative_device_1test_1keypad_1bk_1turn_1on_1jni
  (JNIEnv *, jclass);

/*
 * Class:     com_nbbsw_mmi_test_MMITestNative
 * Method:    device_test_keypad_bk_turn_off_jni
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_bird_mmi_1test_MMITestNative_device_1test_1keypad_1bk_1turn_1off_1jni
  (JNIEnv *, jclass);

/*
 * Class:     com_nbbsw_mmi_test_MMITestNative
 * Method:    device_test_get_barcode_jni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bird_mmi_1test_MMITestNative_device_1test_1get_1barcode_1jni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
