#
# Makefile for misc devices that really don't fit anywhere else.
#


obj-y += ssd2075_hd720_dsi_vdo_lg_qt470hd028sh02_mx2521e_yaao_x28.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/



