#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += fl11281_hd720_dsi_vdo_cmo_gongtai_f050a13603_mx2126e_yaao_x15.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/



