#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += rm68200_hd720_dsi_vdo_inl_zma_f050a13_mx2521e_yaao_x27.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/



