#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += ili9807_qhd_dsi_vdo_ivo_bx_mx2135f_szbd_e5505.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/



