#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += ili9881p_hd720_dsi_vdo_panda_bx_bx500125_mx2135f_szbd_e5018.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/



