#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += rm68200_hd720_auo_ips_vdo_yikuailai_for_e5011.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/


