#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += nt35521_hd720_dsi_vdo_cmi_kyd_fpc055nnh161a1_mx2151e_sft_j5501.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
