#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += ili9806e_fwvga_dsi_vdo_boe_bx_bx45003725c_mx2103_smt.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/



