/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bird_flashlight_BirdFlashlightNative */

#ifndef _Included_com_bird_flashlight_BirdFlashlightNative
#define _Included_com_bird_flashlight_BirdFlashlightNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bird_flashlight_BirdFlashlightNative
 * Method:    isFlashLightOn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_bird_flashlight_BirdFlashlightNative_isFlashLightOn
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
